---
 - name: Playbook to install NGINX
   hosts: Ubuntuserver
   become: yes
   tasks: 
    - name: Ansible apt install tree
      apt:
        name: tree
        state: present
      when: ansible_os_family = "Ubuntu"