---
 - name: Playbook to install NGINX
   hosts: Ubuntuserver
   become: yes
   tasks: 
    - name: Ansible apt install tree
      apt:
        name: tree
        state: present
      become: yes
      when: ansible_os_family == "Debian"
    - name: Ansible apt install tree
      yum:
        name: tree
        state: present
      become: yes
      when: ansible_os_family == "RedHat"