---
 - name: Playbook to install NGINX
   hosts: all
   become: yes
   tasks: 
    - name: Ansible apt install apache2
      apt:
        name: apache2
        state: present
      become: yes
      when: ansible_os_family == "Debian"
    - name: Ansible httpd install readhat
      yum:
        name: httpd
        state: present
      become: yes
      when: ansible_os_family == "RedHat"