---
 - name: Playbook to install NGINX
   hosts: all
   become: true
   tasks: 
    - name: Ansible apt install tree
      apt:
        name: tree
        state: present
        ansible_os_family: "Ubuntu"
    - name: Ansible apt install tree in readhat
      yum:
        name: tree
        state: present
        ansible_os_family: "RedHat"
