---
 - name: Playbook to install NGINX
   hosts: all
   become: true
   tasks: 
    - name: Ansible apt install nginx
      apt:
        name: nginx
        state: present
        ansible_distribution: "Ubuntu"
    - name: Ansible apt install nginx
      yum:
        name: nginx
        state: present
        ansible_distribution: "RedHat"
